/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthWebsitesRouteImport } from './routes/_auth.websites'
import { Route as AuthTranslationsRouteImport } from './routes/_auth.translations'
import { Route as AuthRolesRouteImport } from './routes/_auth.roles'
import { Route as AuthAuditLogsRouteImport } from './routes/_auth.audit-logs'
import { Route as AuthWebsitesIndexRouteImport } from './routes/_auth.websites.index'
import { Route as AuthRolesIndexRouteImport } from './routes/_auth.roles.index'
import { Route as AuthWebsitesWebsiteIdRouteImport } from './routes/_auth.websites.$websiteId'
import { Route as AuthWebsitesWebsiteIdIndexRouteImport } from './routes/_auth.websites.$websiteId.index'
import { Route as AuthWebsitesWebsiteIdMediaRouteImport } from './routes/_auth.websites.$websiteId.media'
import { Route as AuthRolesRoleIdEditRouteImport } from './routes/_auth.roles.$roleId.edit'
import { Route as AuthWebsitesWebsiteIdSchemasIndexRouteImport } from './routes/_auth.websites.$websiteId.schemas.index'
import { Route as AuthWebsitesWebsiteIdSchemasNewRouteImport } from './routes/_auth.websites.$websiteId.schemas.new'
import { Route as AuthWebsitesWebsiteIdSchemasSchemaIdIndexRouteImport } from './routes/_auth.websites.$websiteId.schemas.$schemaId.index'
import { Route as AuthWebsitesWebsiteIdSchemasSchemaIdEditRouteImport } from './routes/_auth.websites.$websiteId.schemas.$schemaId.edit'
import { Route as AuthWebsitesWebsiteIdSchemasSchemaIdEntriesEntryIdRouteImport } from './routes/_auth.websites.$websiteId.schemas.$schemaId.entries.$entryId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWebsitesRoute = AuthWebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTranslationsRoute = AuthTranslationsRouteImport.update({
  id: '/translations',
  path: '/translations',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRolesRoute = AuthRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuditLogsRoute = AuthAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWebsitesIndexRoute = AuthWebsitesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthWebsitesRoute,
} as any)
const AuthRolesIndexRoute = AuthRolesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRolesRoute,
} as any)
const AuthWebsitesWebsiteIdRoute = AuthWebsitesWebsiteIdRouteImport.update({
  id: '/$websiteId',
  path: '/$websiteId',
  getParentRoute: () => AuthWebsitesRoute,
} as any)
const AuthWebsitesWebsiteIdIndexRoute =
  AuthWebsitesWebsiteIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthWebsitesWebsiteIdRoute,
  } as any)
const AuthWebsitesWebsiteIdMediaRoute =
  AuthWebsitesWebsiteIdMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => AuthWebsitesWebsiteIdRoute,
  } as any)
const AuthRolesRoleIdEditRoute = AuthRolesRoleIdEditRouteImport.update({
  id: '/$roleId/edit',
  path: '/$roleId/edit',
  getParentRoute: () => AuthRolesRoute,
} as any)
const AuthWebsitesWebsiteIdSchemasIndexRoute =
  AuthWebsitesWebsiteIdSchemasIndexRouteImport.update({
    id: '/schemas/',
    path: '/schemas/',
    getParentRoute: () => AuthWebsitesWebsiteIdRoute,
  } as any)
const AuthWebsitesWebsiteIdSchemasNewRoute =
  AuthWebsitesWebsiteIdSchemasNewRouteImport.update({
    id: '/schemas/new',
    path: '/schemas/new',
    getParentRoute: () => AuthWebsitesWebsiteIdRoute,
  } as any)
const AuthWebsitesWebsiteIdSchemasSchemaIdIndexRoute =
  AuthWebsitesWebsiteIdSchemasSchemaIdIndexRouteImport.update({
    id: '/schemas/$schemaId/',
    path: '/schemas/$schemaId/',
    getParentRoute: () => AuthWebsitesWebsiteIdRoute,
  } as any)
const AuthWebsitesWebsiteIdSchemasSchemaIdEditRoute =
  AuthWebsitesWebsiteIdSchemasSchemaIdEditRouteImport.update({
    id: '/schemas/$schemaId/edit',
    path: '/schemas/$schemaId/edit',
    getParentRoute: () => AuthWebsitesWebsiteIdRoute,
  } as any)
const AuthWebsitesWebsiteIdSchemasSchemaIdEntriesEntryIdRoute =
  AuthWebsitesWebsiteIdSchemasSchemaIdEntriesEntryIdRouteImport.update({
    id: '/schemas/$schemaId/entries/$entryId',
    path: '/schemas/$schemaId/entries/$entryId',
    getParentRoute: () => AuthWebsitesWebsiteIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit-logs': typeof AuthAuditLogsRoute
  '/roles': typeof AuthRolesRouteWithChildren
  '/translations': typeof AuthTranslationsRoute
  '/websites': typeof AuthWebsitesRouteWithChildren
  '/websites/$websiteId': typeof AuthWebsitesWebsiteIdRouteWithChildren
  '/roles/': typeof AuthRolesIndexRoute
  '/websites/': typeof AuthWebsitesIndexRoute
  '/roles/$roleId/edit': typeof AuthRolesRoleIdEditRoute
  '/websites/$websiteId/media': typeof AuthWebsitesWebsiteIdMediaRoute
  '/websites/$websiteId/': typeof AuthWebsitesWebsiteIdIndexRoute
  '/websites/$websiteId/schemas/new': typeof AuthWebsitesWebsiteIdSchemasNewRoute
  '/websites/$websiteId/schemas/': typeof AuthWebsitesWebsiteIdSchemasIndexRoute
  '/websites/$websiteId/schemas/$schemaId/edit': typeof AuthWebsitesWebsiteIdSchemasSchemaIdEditRoute
  '/websites/$websiteId/schemas/$schemaId/': typeof AuthWebsitesWebsiteIdSchemasSchemaIdIndexRoute
  '/websites/$websiteId/schemas/$schemaId/entries/$entryId': typeof AuthWebsitesWebsiteIdSchemasSchemaIdEntriesEntryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit-logs': typeof AuthAuditLogsRoute
  '/translations': typeof AuthTranslationsRoute
  '/roles': typeof AuthRolesIndexRoute
  '/websites': typeof AuthWebsitesIndexRoute
  '/roles/$roleId/edit': typeof AuthRolesRoleIdEditRoute
  '/websites/$websiteId/media': typeof AuthWebsitesWebsiteIdMediaRoute
  '/websites/$websiteId': typeof AuthWebsitesWebsiteIdIndexRoute
  '/websites/$websiteId/schemas/new': typeof AuthWebsitesWebsiteIdSchemasNewRoute
  '/websites/$websiteId/schemas': typeof AuthWebsitesWebsiteIdSchemasIndexRoute
  '/websites/$websiteId/schemas/$schemaId/edit': typeof AuthWebsitesWebsiteIdSchemasSchemaIdEditRoute
  '/websites/$websiteId/schemas/$schemaId': typeof AuthWebsitesWebsiteIdSchemasSchemaIdIndexRoute
  '/websites/$websiteId/schemas/$schemaId/entries/$entryId': typeof AuthWebsitesWebsiteIdSchemasSchemaIdEntriesEntryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/audit-logs': typeof AuthAuditLogsRoute
  '/_auth/roles': typeof AuthRolesRouteWithChildren
  '/_auth/translations': typeof AuthTranslationsRoute
  '/_auth/websites': typeof AuthWebsitesRouteWithChildren
  '/_auth/websites/$websiteId': typeof AuthWebsitesWebsiteIdRouteWithChildren
  '/_auth/roles/': typeof AuthRolesIndexRoute
  '/_auth/websites/': typeof AuthWebsitesIndexRoute
  '/_auth/roles/$roleId/edit': typeof AuthRolesRoleIdEditRoute
  '/_auth/websites/$websiteId/media': typeof AuthWebsitesWebsiteIdMediaRoute
  '/_auth/websites/$websiteId/': typeof AuthWebsitesWebsiteIdIndexRoute
  '/_auth/websites/$websiteId/schemas/new': typeof AuthWebsitesWebsiteIdSchemasNewRoute
  '/_auth/websites/$websiteId/schemas/': typeof AuthWebsitesWebsiteIdSchemasIndexRoute
  '/_auth/websites/$websiteId/schemas/$schemaId/edit': typeof AuthWebsitesWebsiteIdSchemasSchemaIdEditRoute
  '/_auth/websites/$websiteId/schemas/$schemaId/': typeof AuthWebsitesWebsiteIdSchemasSchemaIdIndexRoute
  '/_auth/websites/$websiteId/schemas/$schemaId/entries/$entryId': typeof AuthWebsitesWebsiteIdSchemasSchemaIdEntriesEntryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit-logs'
    | '/roles'
    | '/translations'
    | '/websites'
    | '/websites/$websiteId'
    | '/roles/'
    | '/websites/'
    | '/roles/$roleId/edit'
    | '/websites/$websiteId/media'
    | '/websites/$websiteId/'
    | '/websites/$websiteId/schemas/new'
    | '/websites/$websiteId/schemas/'
    | '/websites/$websiteId/schemas/$schemaId/edit'
    | '/websites/$websiteId/schemas/$schemaId/'
    | '/websites/$websiteId/schemas/$schemaId/entries/$entryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/audit-logs'
    | '/translations'
    | '/roles'
    | '/websites'
    | '/roles/$roleId/edit'
    | '/websites/$websiteId/media'
    | '/websites/$websiteId'
    | '/websites/$websiteId/schemas/new'
    | '/websites/$websiteId/schemas'
    | '/websites/$websiteId/schemas/$schemaId/edit'
    | '/websites/$websiteId/schemas/$schemaId'
    | '/websites/$websiteId/schemas/$schemaId/entries/$entryId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/audit-logs'
    | '/_auth/roles'
    | '/_auth/translations'
    | '/_auth/websites'
    | '/_auth/websites/$websiteId'
    | '/_auth/roles/'
    | '/_auth/websites/'
    | '/_auth/roles/$roleId/edit'
    | '/_auth/websites/$websiteId/media'
    | '/_auth/websites/$websiteId/'
    | '/_auth/websites/$websiteId/schemas/new'
    | '/_auth/websites/$websiteId/schemas/'
    | '/_auth/websites/$websiteId/schemas/$schemaId/edit'
    | '/_auth/websites/$websiteId/schemas/$schemaId/'
    | '/_auth/websites/$websiteId/schemas/$schemaId/entries/$entryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/websites': {
      id: '/_auth/websites'
      path: '/websites'
      fullPath: '/websites'
      preLoaderRoute: typeof AuthWebsitesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/translations': {
      id: '/_auth/translations'
      path: '/translations'
      fullPath: '/translations'
      preLoaderRoute: typeof AuthTranslationsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/roles': {
      id: '/_auth/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthRolesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/audit-logs': {
      id: '/_auth/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthAuditLogsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/websites/': {
      id: '/_auth/websites/'
      path: '/'
      fullPath: '/websites/'
      preLoaderRoute: typeof AuthWebsitesIndexRouteImport
      parentRoute: typeof AuthWebsitesRoute
    }
    '/_auth/roles/': {
      id: '/_auth/roles/'
      path: '/'
      fullPath: '/roles/'
      preLoaderRoute: typeof AuthRolesIndexRouteImport
      parentRoute: typeof AuthRolesRoute
    }
    '/_auth/websites/$websiteId': {
      id: '/_auth/websites/$websiteId'
      path: '/$websiteId'
      fullPath: '/websites/$websiteId'
      preLoaderRoute: typeof AuthWebsitesWebsiteIdRouteImport
      parentRoute: typeof AuthWebsitesRoute
    }
    '/_auth/websites/$websiteId/': {
      id: '/_auth/websites/$websiteId/'
      path: '/'
      fullPath: '/websites/$websiteId/'
      preLoaderRoute: typeof AuthWebsitesWebsiteIdIndexRouteImport
      parentRoute: typeof AuthWebsitesWebsiteIdRoute
    }
    '/_auth/websites/$websiteId/media': {
      id: '/_auth/websites/$websiteId/media'
      path: '/media'
      fullPath: '/websites/$websiteId/media'
      preLoaderRoute: typeof AuthWebsitesWebsiteIdMediaRouteImport
      parentRoute: typeof AuthWebsitesWebsiteIdRoute
    }
    '/_auth/roles/$roleId/edit': {
      id: '/_auth/roles/$roleId/edit'
      path: '/$roleId/edit'
      fullPath: '/roles/$roleId/edit'
      preLoaderRoute: typeof AuthRolesRoleIdEditRouteImport
      parentRoute: typeof AuthRolesRoute
    }
    '/_auth/websites/$websiteId/schemas/': {
      id: '/_auth/websites/$websiteId/schemas/'
      path: '/schemas'
      fullPath: '/websites/$websiteId/schemas/'
      preLoaderRoute: typeof AuthWebsitesWebsiteIdSchemasIndexRouteImport
      parentRoute: typeof AuthWebsitesWebsiteIdRoute
    }
    '/_auth/websites/$websiteId/schemas/new': {
      id: '/_auth/websites/$websiteId/schemas/new'
      path: '/schemas/new'
      fullPath: '/websites/$websiteId/schemas/new'
      preLoaderRoute: typeof AuthWebsitesWebsiteIdSchemasNewRouteImport
      parentRoute: typeof AuthWebsitesWebsiteIdRoute
    }
    '/_auth/websites/$websiteId/schemas/$schemaId/': {
      id: '/_auth/websites/$websiteId/schemas/$schemaId/'
      path: '/schemas/$schemaId'
      fullPath: '/websites/$websiteId/schemas/$schemaId/'
      preLoaderRoute: typeof AuthWebsitesWebsiteIdSchemasSchemaIdIndexRouteImport
      parentRoute: typeof AuthWebsitesWebsiteIdRoute
    }
    '/_auth/websites/$websiteId/schemas/$schemaId/edit': {
      id: '/_auth/websites/$websiteId/schemas/$schemaId/edit'
      path: '/schemas/$schemaId/edit'
      fullPath: '/websites/$websiteId/schemas/$schemaId/edit'
      preLoaderRoute: typeof AuthWebsitesWebsiteIdSchemasSchemaIdEditRouteImport
      parentRoute: typeof AuthWebsitesWebsiteIdRoute
    }
    '/_auth/websites/$websiteId/schemas/$schemaId/entries/$entryId': {
      id: '/_auth/websites/$websiteId/schemas/$schemaId/entries/$entryId'
      path: '/schemas/$schemaId/entries/$entryId'
      fullPath: '/websites/$websiteId/schemas/$schemaId/entries/$entryId'
      preLoaderRoute: typeof AuthWebsitesWebsiteIdSchemasSchemaIdEntriesEntryIdRouteImport
      parentRoute: typeof AuthWebsitesWebsiteIdRoute
    }
  }
}

interface AuthRolesRouteChildren {
  AuthRolesIndexRoute: typeof AuthRolesIndexRoute
  AuthRolesRoleIdEditRoute: typeof AuthRolesRoleIdEditRoute
}

const AuthRolesRouteChildren: AuthRolesRouteChildren = {
  AuthRolesIndexRoute: AuthRolesIndexRoute,
  AuthRolesRoleIdEditRoute: AuthRolesRoleIdEditRoute,
}

const AuthRolesRouteWithChildren = AuthRolesRoute._addFileChildren(
  AuthRolesRouteChildren,
)

interface AuthWebsitesWebsiteIdRouteChildren {
  AuthWebsitesWebsiteIdMediaRoute: typeof AuthWebsitesWebsiteIdMediaRoute
  AuthWebsitesWebsiteIdIndexRoute: typeof AuthWebsitesWebsiteIdIndexRoute
  AuthWebsitesWebsiteIdSchemasNewRoute: typeof AuthWebsitesWebsiteIdSchemasNewRoute
  AuthWebsitesWebsiteIdSchemasIndexRoute: typeof AuthWebsitesWebsiteIdSchemasIndexRoute
  AuthWebsitesWebsiteIdSchemasSchemaIdEditRoute: typeof AuthWebsitesWebsiteIdSchemasSchemaIdEditRoute
  AuthWebsitesWebsiteIdSchemasSchemaIdIndexRoute: typeof AuthWebsitesWebsiteIdSchemasSchemaIdIndexRoute
  AuthWebsitesWebsiteIdSchemasSchemaIdEntriesEntryIdRoute: typeof AuthWebsitesWebsiteIdSchemasSchemaIdEntriesEntryIdRoute
}

const AuthWebsitesWebsiteIdRouteChildren: AuthWebsitesWebsiteIdRouteChildren = {
  AuthWebsitesWebsiteIdMediaRoute: AuthWebsitesWebsiteIdMediaRoute,
  AuthWebsitesWebsiteIdIndexRoute: AuthWebsitesWebsiteIdIndexRoute,
  AuthWebsitesWebsiteIdSchemasNewRoute: AuthWebsitesWebsiteIdSchemasNewRoute,
  AuthWebsitesWebsiteIdSchemasIndexRoute:
    AuthWebsitesWebsiteIdSchemasIndexRoute,
  AuthWebsitesWebsiteIdSchemasSchemaIdEditRoute:
    AuthWebsitesWebsiteIdSchemasSchemaIdEditRoute,
  AuthWebsitesWebsiteIdSchemasSchemaIdIndexRoute:
    AuthWebsitesWebsiteIdSchemasSchemaIdIndexRoute,
  AuthWebsitesWebsiteIdSchemasSchemaIdEntriesEntryIdRoute:
    AuthWebsitesWebsiteIdSchemasSchemaIdEntriesEntryIdRoute,
}

const AuthWebsitesWebsiteIdRouteWithChildren =
  AuthWebsitesWebsiteIdRoute._addFileChildren(
    AuthWebsitesWebsiteIdRouteChildren,
  )

interface AuthWebsitesRouteChildren {
  AuthWebsitesWebsiteIdRoute: typeof AuthWebsitesWebsiteIdRouteWithChildren
  AuthWebsitesIndexRoute: typeof AuthWebsitesIndexRoute
}

const AuthWebsitesRouteChildren: AuthWebsitesRouteChildren = {
  AuthWebsitesWebsiteIdRoute: AuthWebsitesWebsiteIdRouteWithChildren,
  AuthWebsitesIndexRoute: AuthWebsitesIndexRoute,
}

const AuthWebsitesRouteWithChildren = AuthWebsitesRoute._addFileChildren(
  AuthWebsitesRouteChildren,
)

interface AuthRouteChildren {
  AuthAuditLogsRoute: typeof AuthAuditLogsRoute
  AuthRolesRoute: typeof AuthRolesRouteWithChildren
  AuthTranslationsRoute: typeof AuthTranslationsRoute
  AuthWebsitesRoute: typeof AuthWebsitesRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuditLogsRoute: AuthAuditLogsRoute,
  AuthRolesRoute: AuthRolesRouteWithChildren,
  AuthTranslationsRoute: AuthTranslationsRoute,
  AuthWebsitesRoute: AuthWebsitesRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
